version: '3'
services:
  frontend:
    image: oleksiygontarpersonal/ticket-system:frontend-0.0.0
    build: .
    environment:
      API_URL: http://server.ticket.system:3000
    ports:
      - 80:80

networks:
  default:
    external:
      name: ticket.system
