version: '3'
services:
  db:
    image: oleksiygontarpersonal/ticket-system:db-0.0.0
    build: .
    environment:
      POSTGRES_PASSWORD: super_secret_admin
      APP_USER_PASSWORD: app_secret
    ports:
    - 5432:5432
